unoegohh_site_homepage:
    path:     /{_locale}
    defaults: { _controller: UnoegohhSiteBundle:Default:index }
    requirements:
        _locale: ru|en

unoegohh_site_about:
    path:     /{_locale}/about
    defaults: { _controller: UnoegohhSiteBundle:Default:about }
    requirements:
        _locale: ru|en

unoegohh_site_press:
    path:     /{_locale}/press
    defaults: { _controller: UnoegohhSiteBundle:Default:press }
    requirements:
        _locale: ru|en

unoegohh_site_archive:
    path:     /{_locale}/archive
    defaults: { _controller: UnoegohhSiteBundle:Default:archive }
    requirements:
        _locale: ru|en

unoegohh_site_archive_more:
    path:     /{_locale}/getMoreArchive/{id}
    defaults: { _controller: UnoegohhSiteBundle:Default:getMoreArchive , id:1 }
    requirements:
        _locale: ru|en

unoegohh_site_get_more:
    path:     /{_locale}/getMore/{id}
    defaults: { _controller: UnoegohhSiteBundle:Default:getMore, id:1 }
    requirements:
        _locale: ru|en

unoegohh_site_contacts:
    path:     /{_locale}/contacts
    defaults: { _controller: UnoegohhSiteBundle:Default:contacts }
    requirements:
        _locale: ru|en

unoegohh_site_start:
    path:     /
    defaults: { _controller: UnoegohhSiteBundle:Default:redirect }
